### ISSUE TITLE
[Feature] Create App Package Build (Usage Without Microsoft Store)

### ISSUE THREAD

**Issue by tmpuserforbugreport** [2fast-team/2fast#10]
## Describe the problem this feature would solve

This app is available only through the MS store which is not convenient for many offline of firewall-protected users. 

## Describe the solution

Would you be so kind to build the app for offline installation!

**Comment by jp-weber** [comment]
The current version is now also available on Github🎉 https://github.com/2fast-team/2fast/releases/tag/v1.0.7
