### ISSUE TITLE
Wrong TOPT numbers when datafile.2fa sync through OneDrive

### ISSUE THREAD

**Issue by tranghaviet** [2fast-team/2fast#102]
## Describe the bug

The Desktop app show wrong TOPT numbers when `datafile.2fa` sync through OneDrive

## Steps to Reproduce

1. Install 2Fast from Microsoft Store
2. Manually add an account
3. Sync file through OneDrive to another computer
4. Open 2Fast on another computer has synced `datafile.fa`
5. 2Fast show wrong TOPT numbers

## Expected behavior

2Fast show correct TOPT numbers like on my TOPT phone app.

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [x] Windows 11 22H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
Have you validated that the other computer has the correct time in your Windows 11?

**Comment by tranghaviet** [comment]
The other computer (Laptop) and the computer show wrong TOPT show correct time. The issue disappear when I restore the `datafile.2fa` to the time before I add a new account.
