### ISSUE TITLE
[Feature] Support online syncing with cloud storage providers

### ISSUE THREAD

**Issue by csm10495** [2fast-team/2fast#105]
Support online syncing with cloud storage providers.

## Describe the problem this feature would solve

I'd like to easily sync my MFA tokens on my various devices. If I add or remove one from one device, that should take effect on all.

## Describe the solution

I saw that WebDAV is being worked on, but personally I'd rather have an encrypted file stored on something like Google Drive. So I guess it would need to be able to login with Google or whatever provider we're talking about.

The file stored wouldn't be human readable, etc. since it would require decryption (done by the app with my password).

If we can't access the remote file, (network issue) we would use the local / last downloaded version.

## Describe alternatives you've considered

WebDAV can more or less do this, but I don't really want to personally host or expose a WebDAV server to the world.

I'd rather use my existing cloud storage. It's behind my account, and then after that it's encrypted so even if it somehow leaked, they still need the master password to get anything useful.

## Additional context & Screenshots

Thanks for your consideration.

**Comment by jp-weber** [comment]
Thank you for the feature suggestion.

There are currently no plans to connect the individual cloud storage providers, but to rely on the respective clients (e.g. Google Drive client) to synchronize the files. 

What speaks against using the respective client in your specific scenario?

**Comment by csm10495** [comment]
Fair enough. Thanks.
