### ISSUE TITLE
Scan QR code NS

### ISSUE THREAD

**Issue by D-Scott77** [2fast-team/2fast#109]
## Describe the bug

Trying to add account with "Scan Key-QR-Code" and a black screen appears then an error page appears saying can't get info

## Steps to Reproduce

1. 2fast - two factor authenticator page
2. Go to 'Navigation menu'
3. Click on 'Accounts'
4. Click on 'Add account'
5. Create a new account page appears with 'How should the key be imported?'
6. Click on 'Scan Key-QR-code'
7. Black screen appears with no QR-code
8. Click on screen
9. 
10. See error

## Expected behavior

QR-code to appear and be copied to add datafile

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [X ] Windows 11 22H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
You wanted to activate two-factor authentication for a service? Was a QR code displayed on the website for the service? If this is displayed, you have to switch to the browser after pressing the scan button and wait until the screen darkens slightly and you can draw a rectangle around the qr code
![2fast_qrcode_scan](https://github.com/2fast-team/2fast/assets/10946850/8c9ad5ea-25be-4bab-ba56-d5b8f6e51fe5)
