### ISSUE TITLE
[Feature] Provide installer (exe/msi)

### ISSUE THREAD

**Issue by felsgaertner** [2fast-team/2fast#11]
## Describe the problem this feature would solve

Currently the software is available only in the Windows App store.

## Describe the solution

The Windows store might be blocked by administrators, so I'd like to ask you to provide a release version - e.g. Github release - as an installer, exe or msi.

**Comment by mhellmeier** [comment]
Thanks a lot for your feedback!

A Microsoft Store alternative is already discussed in #10. Besides this, releases are available in this repository:
https://github.com/2fast-team/2fast/releases

**Comment by felsgaertner** [comment]
Sorry, but that is a 318 MB ZIP file, not an installer exe or msi. Do I miss something?

**Comment by jp-weber** [comment]
The installer files (msix) are the content of the zip:
![grafik](https://user-images.githubusercontent.com/10946850/151861757-e1af6a15-a424-4154-b472-6bfda068b4f8.png)
