### ISSUE TITLE
Constantly Get Password Invalid when trying to load datafile

### ISSUE THREAD

**Issue by nla-sean** [2fast-team/2fast#110]
## Describe the bug

Profile was migrated and lost access to the 2FA app, but have a backup datafile. 
Loading this on the start of the app and it accepts password, then complains the "Password invalid". (Can't take screenshot as app blacks out).
"The password saved in this app is invalid for the data file. You may have changed the password in another machine for the data file. **Do you want to change the password now?"

I change the password, occasionally the app crashes, otherwise the Accounts section is empty.

Go to settings, and back again and the password invalid box re-appears.

If the app crashes, after re-opening asks to submit bug report with error
`The system cannot find the file specified. (Exception from HRESULT: 0x80070002)`

## Steps to Reproduce

See above.

## Expected behavior

Load the datafile and if its changing the password, change it and load my codes.

## Screenshots

Can't app blacks out on printscreen and snipping.

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [X] Windows 11 22H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
How was the profile migrated? Have the drives changed? The error message is that the file cannot be found. I cannot understand why the dialog for the password error appears in this context via the initial steps.

I would therefore suggest resetting the app and relinking the data file.

Settings / apps / 2fast / expended settings

**Comment by nla-sean** [comment]
Using a freeware to do the migration, had no other issues with any other apps or data.

Unsure why the file can't be found, its in the same location, and it lets me navigate to it in the app.
Same issue occurs when:
- Moving the file to a new location
- Trying to create a new datafile

I've reset the app, uninstalled and reinstalled the app.

Tried setting up a new datafile and it does the same thing. Seems to be completely broken.

**Comment by nla-sean** [comment]
The app also self closes when attempting to get permission to access storage.

Grant access and it does appear to continue after starting the app again. Can't imagine that is expected behaviour either.

**Comment by jp-weber** [comment]
Then something seems to have gone very wrong during the profile migration. 

What happen if you open the file via double click? The app should be able to load the file correctly through the file association, as a different routine and authorization applies.

**Comment by nla-sean** [comment]
> Then something seems to have gone very wrong during the profile migration.
> 
> What happen if you open the file via double click? The app should be able to load the file correctly through the file association, as a different routine and authorization applies.

That worked.

App still self-closed when clicking on the authorisation button, and the one next to it was pure white.

Seems to be working though :)
