### ISSUE TITLE
Application automatically closes on opening.

### ISSUE THREAD

**Issue by kyuriel** [2fast-team/2fast#114]
## Describe the bug

Upon opening the app, the window shows up briefly for 1-2 seconds with the login screen but immediately closes. Able to briefly move the window by dragging the title bar but unable to interact in any other way before it suddenly closes.

## Steps to Reproduce

1. Opening the 2fast application from the Windows 11 Start menu

## Expected behavior

Normally I'd be able to enter my Windows Hello PIN to proceed but currently the application closes before I'm given the prompt to do so

## Environment

App Version(s):

1.2.7.0

Windows 10/11 Build Number:
- [ ] Windows 10 > May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [x] Windows 11 22H2/23H2 Update (22621.3155)
- [ ] Insider Build ({build_number})

## Additional context

Haven't had to use the application in about a month, needed it today but presented with the issue. This is the first time I've experienced a problem using this program since downloading it years ago. The version I'm on is via the Microsoft Store but can't seem to find any method of contact through there.

**Comment by kyuriel** [comment]
I have somewhat resolved the issue. For whatever reason my Windows Hello stopped working. I tried disabling my current PIN for it and the problem with 2fast automatically closing went away. I was then able to log in using my password for 2fast as opposed to my Windows Hello PIN.

**Comment by jp-weber** [comment]
Thanks for your feedback and the addendum, I hadn't considered that Windows Hello can run into errors here and I will catch them.
