### ISSUE TITLE
Cannot copy 2Fast QR code to clipboard with screenshot tool or scan with 1Passsword

### ISSUE THREAD

**Issue by JasonSanDiego** [2fast-team/2fast#119]
## Describe the bug

When attempting to transfer a TOTP entry into 1Password, I'm unable to use any screen capture tool to get the QR code into the clipboard. The 2Fast screen always turns black.

## Steps to Reproduce

1. In Windows 11, installed via app store
2. Click three dots for an entry in 2Fast
3. Click on Display QR code
4. In 1Password, create a new entry; select one-time password as type; click Scan QR code from clipboard or screen
5. After a few moments, app shows QR code detection failed.
6. Press Print Screen on keyboard; Win11 snipping tool appears
7. 2Fast screen goes black

Same behavior when using another tool like Greenshot. This seems like maybe it's a security feature, but what is it really protecting against? People are rarely going to be showing the QR code unless it's needed.

## Expected behavior

Be able to copy 2Fast into clipboard for "scanning" by 1Password. Or, provide the alphanumeric token that's needed to manually set up TOTP.

## Screenshots

![image](https://github.com/2fast-team/2fast/assets/1314250/34076566-45b5-4793-a1e4-78bc9c5feca3)

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 > May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [X] Windows 11 22H2/23H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
This is a security function that serves in particular to ensure that the generated codes cannot be recorded by third-party software. The generation of QR codes is intended for smartphones, as the mobile application is still under development.

However, there is a temporary way to deactivate the security function:
https://github.com/2fast-team/2fast/wiki/Disable-the-screen-capture-protection-(not-permanent)
