### ISSUE TITLE
No longer generates working 2FA codes after April 2024 

### ISSUE THREAD

**Issue by SimonBrangwin** [2fast-team/2fast#126]
## Describe the bug

I've been using 2fast Windows store app for a 5 or 6 months in conjunction with other 2FA apps to trial it. I am running version 1.2.8.0
It has been working perfectly this entire time until this morning, 2 April 2024. The codes it now generates are invalid. Fortunately, I had registered for 2FA on other apps such as Authy and Microsoft Authenticator as a backup, and they are still generating the correct working codes, so I am not locked out.

I have no idea why the 2FA algorithm in this app has suddenly started failing though.

## Steps to Reproduce

1. Given a Windows 10 Pro version 10.0.19045 environment.
2. Launch 2fast.
3. Select a code from one of the 8 accounts I have loaded (e.g. LinkedIn, Microsoft O365, Azure AD)
4. Try to use it and confirm it failed.
5. Try again but this time use a code generated from Authy and confirm it succeeds.

## Expected behavior

I expect the codes generated from 2fast to be valid 2FA codes.

## Environment

App Version(s): 1.2.8.0

Windows 10/11 Build Number:
- [ ] Windows 10 > May 2020 Update (19041)
- [x] Windows 10 Pro version 10.0.19045
- [ ] Windows 11 21H2 Update (22000)
- [ ] Windows 11 22H2/23H2 Update (22621)
- [ ] Windows 10 Pro version 10.0.19045
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
Hello @SimonBrangwin,

thank you for your issue. An invalid generation of the codes is either due to an incorrect system time or an incorrect secret. Since it had worked so far, synchronising the time should solve the problem.

**Comment by SimonBrangwin** [comment]
Hi @jp-weber 
Thanks for the suggestion. The system clock that I'm testing this on is correct. Interestingly, 7 of the 8 accounts I have loaded are generating correct codes today. The 1 that is generating incorrect codes was previously generating correct ones for 5 months.

I remembered that a few days ago I accidentally clicked the "reload data file" from the hamburger menu below the close app 'X' in the top right title area. I was intending to close the window and missed it. I wouldn't expect reloading the data file would cause this issue though, but that might be helpful if you're looking for a culprit. It did seem to coincide with the issues I've experienced. 
I store the datafile on my OneDrive if that makes any difference. I have checked and my OneDrive is syncing fine.

In any case, I will need to recreate the account by re-enrolling for MFA again. It is an O365 account I have so it shouldn't be difficult.

I realise there's very little information for you to investigate this further so you may want to close this for now. Thanks for all you and the team's work on providing this 2FA app. I chose it because it allows one to display the codes without having to click on them individually. This is a big time saver to be able to see them all at once for me.
