### ISSUE TITLE
[Feature] Standard alphabet casing

### ISSUE THREAD

**Issue by infinotiver** [2fast-team/2fast#129]
## Describe the solution

Currently, in various places on the app ui, different and non uniform casing is used (AABB, aabb, Aabb etc...) . While this won't cause a very large problem, in terms of functionality, It is still recommended to use an uniform case as it enhances UI & UX ( examples of non uniformity given below )

![image](https://github.com/2fast-team/2fast/assets/88645086/1778584c-f4a0-4f9c-8721-e63d3b660288)

due to security reasons, and blockages I couldn't provide screenshots of every instance,
* (Accounts page) Top right bar, `Categories & Filters` , `lock app`, `Reload datafile`
* (About the app) `Show source code of the app`, `rate the app` ....
As seen above, there is irregularity in the casing, some are in Sentence case, others being in lower case etc..

**Comment by jp-weber** [comment]
Implemented in v.1.2.9: https://github.com/2fast-team/2fast/releases/tag/v1.2.9
