### ISSUE TITLE
Security request - do not show all 2fa tokens all the time

### ISSUE THREAD

**Issue by lemmy04** [2fast-team/2fast#13]
I believe it would be better (as in, more secure) if the app would not generate and show all tokens all the time.
Every other 2fa token generator I've used only shows the one token you want to see, and not all of them all the time - you have to click (tap) on the one you need to see the code.

**Comment by jp-weber** [comment]
This can be introduced as an additional option. I would not set this as the default, however, as it only adds value when using the device in public spaces (screen recording preventing is always on).

**Comment by lemmy04** [comment]
> when using the device in public spaces (screen recording preventing is always on).

That's exactly the kind of situation that I was thinking of....

**Comment by jp-weber** [comment]
The feature request is now available in v1.0.9.
