### ISSUE TITLE
[Question] .2fa File | Does it contain the application password?

### ISSUE THREAD

**Issue by lmaooa1043** [2fast-team/2fast#132]
**Hello, I was wondering if the .2fa file that i have saved on my desktop contains my password thats used to open the 2fast app.**

> Sorry if im doing this wrong!

**Comment by lmaooa1043** [comment]
Also, i forgot my password, right now im using the windows pin type of password, if theres anyway to recover my old password, please help me and tell me how!

**Comment by jp-weber** [comment]
Hello @lmaooa1043, you can view your password in the Windows credential manager: https://github.com/2fast-team/2fast/wiki/View-password-for-encryption-on-local-device

**Comment by lmaooa1043** [comment]
Thank you, @jp-weber , I completely forgot about that windows saves it, thank you so much!
