### ISSUE TITLE
OTP Token is wrong since App was updated to [Beta]

### ISSUE THREAD

**Issue by HerrNamenlos123** [2fast-team/2fast#134]
## Describe the bug

I use 2fast for a single OTP login at University. It worked flawlessly for almost a year now, worked every time. However, since a month or so, everytime I try to enter, my university login says "Authentication failed. Die Antwort stimmte für 3 Token nicht überein." I also noticed, the app (installed in Microsoft Store) now says [Beta] in the title bar. I am almost sure it is because of the beta. My OTP on my phone still works fine at University, it is just 2fast that does not work anymore. 

Maybe there was a button "try beta" at some point and I may have clicked on it, but if so, I cannot find a way to switch back. Really, I would be fine if I could just switch back and use the stable version.

## Steps to Reproduce

Well, I cannot really give you my university login...
I do not use 2fast for any other services.

## Expected behavior

Login should work

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 > May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [x] Windows 11 22H2/23H2 Update (22621)
- [ ] Insider Build ({build_number})

Version 1.2.8.0
Title says [Beta]

## Additional context

It would be great if you know what to do with this error message. But really, I would be fine if you could tell me how to downgrade to non-beta because it worked before.

**Comment by HerrNamenlos123** [comment]
What is interesting is that when I enter the OTP from 2fast like I always did in the past, I get the error from above and when I immediately enter another OTP from my Phone I get the error "Authentication failed. wrong OTP-Pin" and this happens forever when i repeatedly enter a working OTP from my Phone. Until I reload the page, then I can enter the correct OTP from my Phone and it works.

So for some reason, the 2fast OTP breaks the login until I reload the page.

**Comment by jp-weber** [comment]
That the app title contains [Beta] is a mistake that was forgotten to change the title in english. Your description of the problem sounds like the Windows system clock is not correct. If you start the synchronisation in the clock settings, it should work again.

**Comment by HerrNamenlos123** [comment]
> That the app title contains [Beta] is a mistake that was forgotten to change the title in english. Your description of the problem sounds like the Windows system clock is not correct. If you start the synchronisation in the clock settings, it should work again.

Thank you for your prompt response! I immediately tried what you said, but unfortunately it did not solve the issue. I went into settings, but it was already synced. Even when syncing again and even restarting PC, it still does the same thing.

**Comment by jp-weber** [comment]
> Will the "Beta" in the title be removed soon? We want to use this tool, but without Beta in the title. Hope you can help with this?

Yes, with the newest version (1.2.9) the title will be fixed. Also I re uploaded the installer with the title fix on github:
https://github.com/2fast-team/2fast/releases/tag/v1.2.8
In the Microsoft Store I cannot fix this with the same version, only a new version is possible to update the store submission.


> What is interesting is that when I enter the OTP from 2fast like I always did in the past, [...]

This is very strange, because nothing has changed in the core logic. Are the same keys displayed on the smartphone and on the PC app within several minutes, or are they always different?

**Comment by HerrNamenlos123** [comment]
This issue is resolved for me. I updated the app and [beta] is now removed, but the OTP still did not work. I had to completely remove the token and reimport it from the online service. It works fine now for me.

This issue can be closed from my side.
