### ISSUE TITLE
{Beta] 2fast Two Factor Authenticator - Error Message

### ISSUE THREAD

**Issue by concepcion122** [2fast-team/2fast#135]
## Describe the bug  -  Error Message - **The system cannot find the drive specified. (Exception from HRESULT: 0x8007000F)**
**#The system cannot find the drive specified. (Exception from HRESULT: 0x8007000F)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Project2FA.Services.DataService.<CheckLocalDatafile>d__70.MoveNext() + 0xb56**

## Steps to Reproduce

**Sorry, not really sure what you want here. I used the app, as i have for months, but this time it gave me the error message pasted above. I closed the app a couple of times, repeated, but the problem persisted.**
1. Given the following environment
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

## Expected behavior
**I expect the app to spit out a 2 factor authenticator number**

## Screenshots
**Weird thing happens when I do a screenshot - the message box comes up totally black.**

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 > May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Windows 11 22H2/23H2 Update (22621) **- it's one of the Windows 11. As I can't get into the app, I can't confirm which.**
- [ ] Insider Build ({build_number})

**Comment by concepcion122** [comment]
I restarted my computer and the problem disappeared. App is now working.

**Comment by jp-weber** [comment]
"The system cannot find the drive specified"
Where did you save your 2fa file? Windows could not find and access the drive here.

**Comment by concepcion122** [comment]
Thanks Jan.
It's all good now. I just had to restart my computer.

Elizabeth
