### ISSUE TITLE
[Feature] Auswählbare Algorithmen bei TOTP Einträgen 

### ISSUE THREAD

**Issue by TheRevolutiooN** [2fast-team/2fast#14]
## Describe the problem this feature would solve

Beim Eintragen eines Schlüssels wird standardmäßig ein Hash-Algorithmus verwendet. Beim Scannen eines QR-Codes wird die jeweilige Verschlüsselung aus dem QR-Code erkannt. Es wäre sehr hilfreich, wenn beim Manuellen Eintragen eines Schlüssels auswählbar ist, welche Verschlüsselung dieser verwendet (SHA1, SHA256, SHA512 usw.). 

## Describe the solution

Beim Eintragen eines neuen Accounts, könnte unter dem Geheimschlüssel-Feld ein Dropdown Menu sein mit den verschiedenen Hash-Algorithmen. 

## Additional context & Screenshots

Ähnlich wie hier, stelle ich mir vor.
![image](https://user-images.githubusercontent.com/48918052/161289627-6f1a3ca4-6058-439f-982f-b3feef9a270e.png)

**Comment by mhellmeier** [comment]
Thanks a lot for your feedback! We have to keep in mind that there are a lot of users who don't know what a hash algorithm is.

**Comment by TheRevolutiooN** [comment]
Thanks for the fast reply. That's true, but maybe as a feature that can be enabled, but is disabled by default. Just a suggestion. There is no totp windows app with that feature I know of.Am 02.04.22, 16:09 schrieb Malte Hellmeier ***@***.***>:

   
  Thanks a lot for your feedback! We have to keep in mind that there are a lot of users who don't know what a hash algorithm is.

**Comment by jp-weber** [comment]
I have implemented the settings as follows, the implementation will probably be released in version 1.1 with the support of account icons and WebDAV.
![grafik](https://user-images.githubusercontent.com/10946850/161604888-18a84fce-9bde-45e9-99a0-f14345ba937b.png)

**Comment by jp-weber** [comment]
feature added with version 1.1.0 https://github.com/2fast-team/2fast/releases/tag/v1.1.0 🎉
