### ISSUE TITLE
cant open authenticator

### ISSUE THREAD

**Issue by chixonator** [2fast-team/2fast#140]
The cloud file provider is not running. (Exception from HRESULT: 0x8007016A)

get this error after trying to open the app and login, also on login its gives me a "password invalid" prompt and then when i try to change my password the program crashes.

most recent version from site

windows 10 version 22h2

**Comment by jp-weber** [comment]
Do you have your data file on OneDrive? According to the error, there is a problem with your OneDrive client. Is the client running? 
https://answers.microsoft.com/en-us/windows/forum/all/error-0x8007016a-the-cloud-file-provider-is-not/7e1a5146-c93f-4787-acc0-c322683b0d9e

> get this error after trying to open the app and login, also on login its gives me a "password invalid" prompt and then when i try to change my password the program crashes.

The dialog call with the password change should not actually occur.

**Comment by chixonator** [comment]
resigning into my onedrive fixed the issue, thank you
