### ISSUE TITLE
App-Certificate no longer valid (expired 2022-04-10)

### ISSUE THREAD

**Issue by Schmittfinger** [2fast-team/2fast#15]
## Describe the bug

The App-Certificate (Project2FA.UWP_1.0.9.0_x86_x64_arm_arm64.cer) is no longer valid (expired 2022-04-10) - so no installation (install.ps1) is possible.

I tried the newest version 1.0.9 (https://github.com/2fast-team/2fast/releases/tag/v1.0.9)

The error-message is like this (on a german system):

PS C:\src\Project2FA.UWP_1.0.9.0_Test> .\Install.ps1
Bundle gefunden: C:\src\Project2FA.UWP_1.0.9.0_Test\Project2FA.UWP_1.0.9.0_x86_x64_arm_arm64.msixbundle
Zertifikat gefunden: C:\src\Project2FA.UWP_1.0.9.0_Test\Project2FA.UWP_1.0.9.0_x86_x64_arm_arm64.cer

Fehler: Das Entwicklerzertifikat "C:\src\Project2FA.UWP_1.0.9.0_Test\Project2FA.UWP_1.0.9.0_x86_x64_arm_arm64.cer" ist abgelaufen. Eine mögliche Ursache ist, dass die Systemuhr nicht auf das richtige Datum und die richtige Uhrzeit eingestellt ist. Wenden Sie sich an den App-Inhaber, damit dieser ein Paket oder Bundle mit einem gültigen Zertifikat erstellt, wenn die Systemeinstellungen richtig sind.

Drücken Sie die Eingabetaste, um den Vorgang fortzusetzen...:

Please renew your development-certificate to fix this bug.

Kind regards,
Sebastian

**Comment by jp-weber** [comment]
Thanks for reporting. I have re-uploaded the certificate with the setup 🙂
