### ISSUE TITLE
Spanish language is Fused with French

### ISSUE THREAD

**Issue by maxii1996** [2fast-team/2fast#167]
## Steps to Reproduce

1. Given the following environment
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

## Environment

App Version(s): 1.3.1.0

Windows 10/11 Build Number:
- [x] Windows 11 22H2/23H2 Update (22621)

## Additional context

Spanish Language Problem

Problem:

**The Spanish Translation is incorrect.**

As you can see in the translation:

https://github.com/2fast-team/2fast/blob/9c8ec3fa892dd9ed12d2dd7692059254a578833c/Project2FA.Shared/Strings/es/Resources.resw#L1316

**The translation into Spanish is wrong. Several lines of Spanish and French have been combined.
Please, I request a language review and correction.
Thank you.**

**Comment by jp-weber** [comment]
Thank you for your feedback. I renew the translation for spanish and will release the fix with v1.3.2:
https://github.com/2fast-team/2fast/commit/2f9823a4274bc2a293a1370d41b49ffba169b4d9

**Comment by jp-weber** [comment]
Fixed with version v1.3.2: https://github.com/2fast-team/2fast/releases/tag/v1.3.2

**Comment by maxii1996** [comment]
Thanks you very much! @jp-weber And a small question, do you know when the phone app (android) it will be available for download?
