### ISSUE TITLE
Crash just hovering mouse over 'copy' button

### ISSUE THREAD

**Issue by Paulrba** [2fast-team/2fast#169]
Every time I open the app, as soon as I hover over the copy button my windows cursor transforms to the busy scrolling icon and the 2fast app crashes (just closes down) 

This can happen 3 or 4 times before I can eventually copy the code I need to the paste buffer

Not sure if this makes any difference but the account is for splashtop remote access software

## Steps to Reproduce

1. Given the following environment
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

## Expected behavior
Every time I open the app as soon as I go to 

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 > May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [x] Windows 11 22H2/23H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
Hello,

on which version of Windows do you have the problem and which language is being used? 

There is an item for error logging in the settings under Functions. Please enter the content of the called log here.

**Comment by Paulrba** [comment]
hi. its windows 11 pro and there are no crash reports!
it just did it again now so i checked for the report on the next login
the application just hangs and closes. im using trend antivirus if this is pertinent

**Comment by NoMoreUsernamesAvailable** [comment]
I can confirm this bug. We use the 2fast Windows app in our company **on different hardware** and we sometimes suffer extremely from these crashes. Some days the Reliability Monitor is full of 2fast crashes and it takes half a dozen attempts before 2fast finally works again. In the app itself there is no error log available.

### Description of the bug and steps to reproduce

After opening the app, everything stays fine as long as you don't interact with the 2fast user interface. However, as soon as you hover the mouse pointer over the copy button, for example, the app crashes immediately. Sometimes the program works again without errors after the second, third or fourth attempt.

Resetting the app always helps (at least once for the next start-up), but of course you then have to do all the settings again. The repair function unfortunately doesn't work. But the crashes don't always occur either; sometimes you have a few days of peace before it starts again.

### Screenshots

![2fast crash](https://github.com/user-attachments/assets/28cc8d1d-c1d8-4840-88b8-b5161a7b498e)

### Environment

App version(s): 1.3.3.0 and older

Windows 10/11 Build Number: Windows 11 Pro 23H2 and older (**in German language**)

**This problem has existed for at least a year, so not only the latest versions of the app and Windows are affected**

**Comment by jp-weber** [comment]
Thanks for emphasising this again. 

To find the source of the error is difficult in this context. Something must be different for you to be able to reproduce the error on a larger scale. I have not been able to reproduce the problem so far, from Windows 10 22H2 to Windows 11 24H2.

Was a test running without group policies and domain join, whether the error can be reproduced from here?

Was an app log also written with the crash? via in app settings or cmd:
https://github.com/2fast-team/2fast/wiki/Open-(error)-log-via-cmd

**Comment by NoMoreUsernamesAvailable** [comment]
> Was a test running without group policies and domain join, whether the error can be reproduced from here?

The crashes don't just happen on our client computers in a domain environment. They also happen on my private PC at home - although much less often.

> Was an app log also written with the crash? via in app settings or cmd: https://github.com/2fast-team/2fast/wiki/Open-(error)-log-via-cmd

No app log was written

> @Paulrba It shouldn't be because of Trend Micro, other users also use it.

And we don't use Trend Micro at all. Maybe the problem is caused by another software that is installed on all affected devices, or by a special Windows setting?


Another thing I noticed: Sometimes it seems as if the problem can be solved (at least temporarily) by leaving the 2fast app alone for a few minutes directly after starting it (BEFORE entering the password).

**Comment by jp-weber** [comment]
I have modified the binding for the tooltips in the newest preview version. I would be pleased if you would test this version:

https://github.com/2fast-team/2fast/releases/tag/v1.3.4

**Comment by NoMoreUsernamesAvailable** [comment]
> I have modified the binding for the tooltips in the newest preview version. I would be pleased if you would test this version:

Thank you, we will test the preview version on some clients 👍

**Comment by NoMoreUsernamesAvailable** [comment]
Update: So far it looks very promising. We have been testing the preview version on various clients over the last few days and so far the app has not crashed once.

**Comment by jp-weber** [comment]
Thank you for your feedback, in the next few days, the update will be available in the store. Meanwhile the RC version is ready for the last tests.

Implemented with v1.3.4: https://github.com/2fast-team/2fast/releases/tag/v1.3.4-rc1
