### ISSUE TITLE
Can't install 2fast silently via PowerShell or via other methods!

### ISSUE THREAD

**Issue by mart-ak** [2fast-team/2fast#170]
We are looking to install 2 Fast silently on our clients using Ivanti. However, we have encountered an issue with deploying it via PowerShell. Could you please check this for us or suggest an alternative method for a silent installation? See print screen!
![image](https://github.com/user-attachments/assets/360e4e99-3c29-4597-a29b-3c0088720dff)

## Steps to Reproduce

1. Given the following environment
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

## Screenshots

![image](https://github.com/user-attachments/assets/360e4e99-3c29-4597-a29b-3c0088720dff)
![image](https://github.com/user-attachments/assets/9fe8b2ae-f45d-4d88-8139-cc6be3ea350a)

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 11 23H2 Update (22631)
- [ ] Insider Build 22631.4169

**Comment by jp-weber** [comment]
Hello @mart-ak,

I see that you run PowerShell as admin. Please try this as non-admin user based on:
https://github.com/microsoft/winget-cli/issues/3303#issuecomment-1580934523
