### ISSUE TITLE
Black screen over the app when accessed by RDP, Anydesk, etc.

### ISSUE THREAD

**Issue by Javo02051974** [2fast-team/2fast#173]
![Black screen](https://github.com/user-attachments/assets/892469bb-d2b1-435f-a343-ca43455c23d6)

## Describe the bug
When accessed to the PC with the 2fas two authenticator installed,  the app shows a black rectangle over it.

## Steps to Reproduce

1. Given the following environment
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

## Environment

App Version(s):

Windows 10/11 Build Number:
- [x] Windows 10 > May 2020 Update (19041)
- [x] Windows 11 21H2 Update (22000)
- [x] Windows 11 22H2/23H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
Hello,

this is a security feature, if you want to disable this for remote sessions, it is possible. The app can be launched with this configuration with a command:
https://github.com/2fast-team/2fast/wiki/Disable-the-screen-capture-protection-(not-permanent)
