### ISSUE TITLE
[Feature] Support for Custom TOTP Time Periods

### ISSUE THREAD

**Issue by pyron83** [2fast-team/2fast#180]
Some TOTP implementations operate with time periods other than the default 30 seconds (e.g., 60 seconds or other intervals). Adding an option to configure custom time periods would enhance flexibility and compatibility with a broader range of TOTP solutions. For instance, older applications, like the discontinued Winauth 3.6.2 beta, included this feature.

**Comment by jp-weber** [comment]
Thank you for your feature request. Manual setting is currently not possible, but the time period is already taken into account when the QR code is read out:

https://github.com/2fast-team/2fast/blob/master/Project2FA.Shared/ViewModels/Base/AddAccountViewModelBase.cs#L621

Manual setting will be available in the next update.

**Comment by jp-weber** [comment]
Implemented with v1.3.4: https://github.com/2fast-team/2fast/releases/tag/v1.3.4-rc1
