### ISSUE TITLE
when open the app it becomes backscreen windows.

### ISSUE THREAD

**Issue by CNIWhiteTiger** [2fast-team/2fast#19]
Hello Support,

will you please check and let me know why this app becomes a black screen window when I am executing this app.
when I minimize and maximize if show the visual for 1 sec and then go in black scren.

![image](https://user-images.githubusercontent.com/90857016/170577540-113a9a91-8aca-41c2-ac9f-056d0fcfd26b.png)

here is my system info

System Information
------------------
      Time of this report: 5/26/2022, 16:48:51
             Machine name: WVDSH-6
               Machine Id: {6F850FCD-057F-428D-BE11-104DEC749FF9}
         Operating System: Windows 10 Enterprise for Virtual Desktops 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)
                 Language: English (Regional Setting: English)
      System Manufacturer: Microsoft Corporation
             System Model: Virtual Machine
                     BIOS: Hyper-V UEFI Release v4.1 (type: UEFI)
                Processor: Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (2 CPUs), ~2.8GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16382MB RAM
                Page File: 3627MB used, 15187MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Not Available
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.0.8
           DxDiag Version: 10.00.19041.0928 64bit Unicode

**Comment by jp-weber** [comment]
Do you connect to the device via RDP? In this case the security function is activated that block the app content as recording. The same happens when the screen is shared with MS Teams or other programm, and the app is visible.

**Comment by CNIWhiteTiger** [comment]
Hello support,

I am using in on wvd azure but i was logged in on local desktop not via RDS session.

Will you please suggest if we must add precaution or any exception we have to add?.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jp-weber** [comment]
A workaround for the issue is the deactivation of the screen capture protection:
https://github.com/2fast-team/2fast/wiki/Disable-the-screen-capture-protection-(not-permanent)
