### ISSUE TITLE
System.Exception: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)

### ISSUE THREAD

**Issue by vertigo220** [2fast-team/2fast#190]
## Describe the bug

App crashed when trying to use scanner

## Steps to Reproduce

Create new and select scanner, app crashed

Don't crash

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ x] Windows 10 > Version 22H2 (OS Build 19045.4894)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Windows 11 22H2/23H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
Hello,

this is a problem between the Windows component to scan the QR code and the 2fast app. Have you tried to google the HRESULT? For example: https://www.ionos.com/digitalguide/server/configuration/the-rpc-server-is-unavailable/

**Comment by vertigo220** [comment]
"DCOM Server Process Launcher" and "Remote Procedure Call (RPC)" services are running, so the fix proposed by that site doesn't apply. "Remote Procedure Call (RPC) Locator" service isn't running, but no indication it needs to be. Also, regardless of the source of the problem, 2fast should ideally handle such an error with more grace, rather than just crashing.

**Comment by jp-weber** [comment]
This potential error will be catched in the next update and the user will be informed of a problem.

**Comment by jp-weber** [comment]
Fixed with v1.3.4: https://github.com/2fast-team/2fast/releases/tag/v1.3.4-rc1
