### ISSUE TITLE
Data file Password with space character fails - Bug?

### ISSUE THREAD

**Issue by siperi** [2fast-team/2fast#21]
Hello,

I have set a data file password that contains a space character. The login is not possible (the password does not match the password of the data file). If I write the password without the space, I can log in.

Example:
Data file password set: Abc Def!
App closed. App started. Login with Abc Def! failed.
Log on with AbcDef! successful (it was a lucky guess).

Uninstalled the app, reinstalled the app, and created a new Data file with a password containing a space character - failure reoccurred.

Regards, Peter

**Comment by jp-weber** [comment]
Hi,

there was once a problem where users accidentally entered a blank at the beginning. This was intercepted in the source code (all blanks). I think I can reverse this as the case is unlikely and may also be deliberate. In version 1.1.1 this will be fixed. 

Remember that the saved password is still 'AbcDef! This can be changed in the settings/datafile with v1.1.1.
