### ISSUE TITLE
Is this app code signed?

### ISSUE THREAD

**Issue by dtantono** [2fast-team/2fast#26]
## Steps to Reproduce

1. Given the following environment which is windows 10
2. Go to https://github.com/2fast-team/2fast/releases/tag/v1.1.0
3. Double click on the zip file
4. Double click the msisxbundle file
5. Windows Smartscreen appears

## Expected behavior

That windows smartscreen appears

## Screenshots

<img width="576" alt="Untitled" src="https://user-images.githubusercontent.com/29157187/184353281-1ea02e62-3f8e-44b2-a1ae-cc0c643c9c64.png">

## Environment

App Version(s):

Windows 10 Build Number:19044.1826

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
Thank you for bring this up. 

I created a wiki for this.

https://github.com/2fast-team/2fast/wiki/How-to-install-.msix-package
