### ISSUE TITLE
[Feature]Option to remove automatic logout after inactivity

### ISSUE THREAD

**Issue by dtantono** [2fast-team/2fast#27]
## Describe the problem this feature would solve

after couple of minutes the app sudennly locked out and I need to input the password again on my personal computer. that is quite a hassle

on the Settings there should be an option to remove the automatic lock. So, we can still use the app without input the password again on personal computer

**Comment by jp-weber** [comment]
This feature will be implemented with version 1.2.

![grafik](https://user-images.githubusercontent.com/10946850/190914356-4d772123-7bb6-40e7-9fb5-e2f6c233df22.png)

**Comment by jp-weber** [comment]
Now implemented in version 1.2.0 https://github.com/2fast-team/2fast/releases/tag/v1.2.0 🎉
