### ISSUE TITLE
Exception of type 'System.Exception' was thrown.

### ISSUE THREAD

**Issue by MoscoeMo** [2fast-team/2fast#31]
## Steps to Reproduce

1. Given the following environment
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

## Environment

App Version(s):

Windows 10/11 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Insider Build ({build_number})

**Comment by mhellmeier** [comment]
Please describe the bug and fill out the entire template so that we are able to reproduce and fix it, thanks a lot!
