### ISSUE TITLE
Exception of type 'System.Exception' was thrown.

### ISSUE THREAD

**Issue by MoscoeMo** [2fast-team/2fast#32]
## I tried to save a key code to the authenticator app and later on it shows error "Exception of type 'System.Exception' was thrown." 
It also says my password is not correct when i tried to loading file from storage. And right now, i  am locked out of my accounts. 

"An unhandlled error occoured the last time the app was used, please submit the error details which can be seen in the box via the ffedback hub, or use the eero meeesage via Github"
## Steps to Reproduce

1. Given the following environment
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

## Environment

App Version(s): I just reinstalled the app and now, my password is not working. after putting password, it automatically closses and when I click again, it shows Exception of type 'System.Exception' was thrown

Windows 10/11 Build Number: Windows 10 Home Single Language 
![IMG_1018](https://user-images.githubusercontent.com/116969050/199178237-4f799e39-6b18-4ceb-9c28-34f9fdb4455f.JPG)
![IMG_1018](https://user-images.githubusercontent.com/116969050/199180860-2a4e4eb9-376a-4536-9658-31013b47d1c4.JPG)
19044.2130

**Comment by MoscoeMo** [comment]
https://user-images.githubusercontent.com/116969050/199181769-d57ed100-7658-4db4-aa66-20994abee73b.mp4

**Comment by jp-weber** [comment]
@MoscoeMo 
How long have you been using the app? Do have you updated the app from an older version? Since when has this problem existed?

I would suggest to do these steps to fix the problem:
1. reset the app and the data: 
![grafik](https://user-images.githubusercontent.com/10946850/199310845-b624b409-6667-49b6-8d88-bb52a8cb0063.png)
2. If the password is still invalid, you can see the saved password from the last install in the credential manager:
![grafik](https://user-images.githubusercontent.com/10946850/199311342-10dc24b7-fc35-425d-8837-9e5f0d8147e4.png)

**Comment by MoscoeMo** [comment]
Thanks for your response. I have typed the password from the windows credential and it still shows the same. I’m I selecting the wrong directory file? It’s a little confusing


Sent from Yahoo Mail for iPhone


On Wednesday, November 2, 2022, 12:07 am, Jan Philipp Weber ***@***.***> wrote:




@MoscoeMo
How long have you been using the app? Do have you updated the app from an older version? Since when has this problem existed?

I would suggest to do these steps to fix the problem:
   
   - reset the app and the data:   

   - If the password is still invalid, you can see the saved password from the last install in the credential manager:

**Comment by MoscoeMo** [comment]
How can I find the main directory file? I have saved it on my computer D:/ drive earlier but at the moment. Can’t find it. I have seen a name which looks like the database file but doesn’t work with 2Fas authenticator 


Sent from Yahoo Mail for iPhone


On Wednesday, November 2, 2022, 12:20 am, Ebere Ogbodo ***@***.***> wrote:

Thanks for your response. I have typed the password from the windows credential and it still shows the same. I’m I selecting the wrong directory file? It’s a little confusing


Sent from Yahoo Mail for iPhone


On Wednesday, November 2, 2022, 12:07 am, Jan Philipp Weber ***@***.***> wrote:




@MoscoeMo
How long have you been using the app? Do have you updated the app from an older version? Since when has this problem existed?

I would suggest to do these steps to fix the problem:
   
   - reset the app and the data:   

   - If the password is still invalid, you can see the saved password from the last install in the credential manager:
