### ISSUE TITLE
Take screenshots or remote control black Window

### ISSUE THREAD

**Issue by vgvdaun** [2fast-team/2fast#47]
Hi, 

we currently have the problem that we cannot take screenshots or remote maintenance for the application. I'm assuming it's a security feature. Is there an option to temporarily disable this feature?

Thanks!

**Comment by jp-weber** [comment]
Hello, 

yes it is a security feature. Based on the request I can implement an command line call to disable for the start this feature (only with this call). The user will notify in the app with red text, that the feature was disabled.

**Comment by vgvdaun** [comment]
Hello jp-weber,

that would be a very good idea. Could you let us know (as soon as the feature is available) and describe how the call works afterwards?

Thanks very much!

**Comment by jp-weber** [comment]
I have now implemented the functionality and will probably release the new version next week when the tests are completed.
The command to enable or disable the screen capture function is:
```start twofastauth://config/set?IsScreenCaptureEnabled=true```

**Comment by ademdal** [comment]
Hello jp-weber,
Could you please explain how we can run this command for Microsoft Store application as well?
Many thanks!

**Comment by jp-weber** [comment]
@ademdal The feature will be generally available next week with the new version 1.2.3. A corresponding wiki entry will also be created here on Github.

**Comment by jp-weber** [comment]
The new version is now in the store and in the next days for all available. See the wiki entry for the new feature: https://github.com/2fast-team/2fast/wiki/Disable-the-screen-capture-protection-(not-permanent)
