### ISSUE TITLE
Google authenticator code did not get recognized

### ISSUE THREAD

**Issue by eslafur** [2fast-team/2fast#49]
i transferred multiple codes to 2fast today, two of which did not get recognized on importing.

i can give one of them as example since i changed the code now and it is for a internal server.
![grafik](https://user-images.githubusercontent.com/16470950/219768247-bcef8bc2-fe50-4a24-9e57-a622b3fe5da0.png)

the resulting secret should be V3XWDLH6ZWDPUEGMXNOD5MU7EG656DIL
but i only get an empty screen after selecting the qr code
![grafik](https://user-images.githubusercontent.com/16470950/219769350-6778b204-64b5-45ce-9dae-6e6021571d73.png)

The other not scanable code came from a microsoft account i don't want to share that code for obvious reasons.

**Comment by jp-weber** [comment]
Thank you for posting your problem. I can confirm the error, which is based in an unnecessary encoding of the string with ```HttpUtility.ParseQueryString```.

I have fixed the bug and will publish this with version 1.2.3.
![grafik](https://user-images.githubusercontent.com/10946850/219852455-ff6d078a-200e-40d9-83bd-d5367043f10b.png)

**Comment by eslafur** [comment]
all codes have been exported from the Google authenticator app, so i am pretty confident that they had the same encoding/format.

**Comment by jp-weber** [comment]
@eslafur 
Then I have misunderstood this point. please try once whether the Microsoft account is now also displayed in the import when you use the new version (1.2.3).
