### ISSUE TITLE
"Display QR Code" feature produces invalid QR codes

### ISSUE THREAD

**Issue by dmjohnsson23** [2fast-team/2fast#55]
## Describe the bug

The "Display QR Code" feature appears to have stopped working with a recent update

## Steps to Reproduce

1. Scan a QR code using 2fast to create a new account
2. Click "Display QR Code" in the menu for the newly created account
3. Scan that code using FreeOTP on Android
4. FreeOTP reports an invalid QR code

I also tried scanning the code using Aegis Authenticator to verify that that the bug is with 2fast rather than FreeOTP.

This worked as expected in a previous version of the application, though I'm not sure which version.

## Expected behavior

I would expect the feature to show the same or equivalent QR code as was scanned initially, so that I can use my 1-time passwords on both devices.

## Environment

App Version(s): 1.2.3.0

Windows 10/11 Build Number: Windows 10 version 21H2 build number 19044.2728

**Comment by jp-weber** [comment]
The issue is fixed with the newest commit. The fix wille be available in the next days with the version 1.2.4.
