### ISSUE TITLE
Some verification codes are always failed to verify

### ISSUE THREAD

**Issue by remy727** [2fast-team/2fast#57]
I am using 2fast `1.2.3`

But recently I noticed some verification codes of already registered account(Especially **Heroku**, **Postman**) are always failed to verify.
I tried to remove the account and add account again but I still can't verify the code.
I tried other app like Google Authenticator chrome extension but it worked.

I saw you released `1.2.4` but I am not getting updates from Microsoft Store yet.

Any thoughts when I can upgrade to `1.2.4`?

**Comment by jp-weber** [comment]
Version 1.2.4 had to be withdrawn due to a problem with older, unchanged data files: #56
A bug-fixed version is currently being verified in the Microsoft Store.

**Comment by jp-weber** [comment]
I checked the different services and cannot find any problems with the import and the verification. Is the problem still present for you?

**Comment by remy727** [comment]
Hi @jp-weber, I am still having issues with Heroku.

**Comment by jp-weber** [comment]
I have created an account again and the verification works perfectly => closed
Generator for one-time passwords:
![grafik](https://user-images.githubusercontent.com/10946850/235303204-e9c157d6-23a4-4881-b5e1-c5ead7f49a5f.png)


Is the system time on your computer correct or synchronised with an NTP server?
