### ISSUE TITLE
forgot password how to reset

### ISSUE THREAD

**Issue by johncblacker** [2fast-team/2fast#6]
How can I reset the password?  I forgot the one I used on installation - MY BAD!

**Comment by johncblacker** [comment]
I just deleted the app and reinstalled it; but in the initial setup I was trying to figure out how to set it up for paypal but couldn’t figure it out.

It was asking for something from paypal which I can’t get into, so I’m stuck.  Where are the instructions or directions?

**Comment by mhellmeier** [comment]
> but in the initial setup I was trying to figure out how to set it up for paypal but couldn’t figure it out. It was asking for something from paypal which I can’t get into, so I’m stuck.

I am sorry but we cannot provide support for specific 3rd party services. The app itself implements the TOTP standard and therefore allows it to work with every website and service that uses it.


> Where are the instructions or directions?

Please check the FAQs of the respective service or ask support for help. If they support external TOTP apps, 2fast will work.
For your specific service, this may help:
https://www.paypal.com/us/smarthelp/article/faq4057
