### ISSUE TITLE
Codes not working on Microsoft website under Windows 10 VM under QEMU/KVM

### ISSUE THREAD

**Issue by NinCollin** [2fast-team/2fast#69]
## Describe the bug

I've been using 2fast for several months between a couple different Windows 10 installations on bare hardware for logging into an organizational Microsoft account. In the past, all I've had to do is migrate my datafile over to new Windows installations, and it's worked flawlessly. 

However, today I decided to install Windows 10 in a VM with virt-manager (QEMU/KVM) under Arch Linux. 2fast installs and loads my data file successfully (and starts generating codes) but everytime I try to use one on https://login.microsoftonline.com/, I receive the error 
`You didn't enter the expected verification code. Please try again.`
This occurs when entering the code both from a browser (Chrome) within the Windows 10 VM, and when entering the code in a browser outside the VM.

## Steps to Reproduce

1. Install Windows 10 Pro 22H2 using `virt-manager` under QEMU/KVM on Arch Linux 
2. Install 2fast from the Microsoft Store
3. Load existing data file
4. Attempt to sign into a Microsoft account on https://login.microsoftonline.com/ that requires an Authenticator App
5. Enter code from 2fast from inside the VM
6. Receive the error

## Environment
![image](https://github.com/2fast-team/2fast/assets/36493269/a1aa93d0-ea9a-42a0-8da4-d02057be1bce)

App Version(s):

Windows 10/11 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [x] Windows 10 22H2 Update 
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
To me it sounds like a local time problem with the system. The generated code is correct, but no longer valid after the error message. Can you confirm that the time in the vm is correct?

**Comment by NinCollin** [comment]
The time seemed right, but set to the wrong timezone. Changing the timezone to the correct one and resyncing the clock fixed the issue. Thanks!
