### ISSUE TITLE
Do not ask for extra permission on windows

### ISSUE THREAD

**Issue by LinoBarreca** [2fast-team/2fast#7]
In the dialog of the database creation you should add a button to create the DB in a "predefined location" to which the app already has access to
https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions
without requiring the user to give consent to unlimited filesystem access.

**Comment by jp-weber** [comment]
If you mean the access cache via the FilePicker, this does not work reliably if the data file is located in a folder that is synchronized by a cloud client and the IDs of the folders change.

**Comment by LinoBarreca** [comment]
Wait.
