### ISSUE TITLE
[Feature] Support Yubikey

### ISSUE THREAD

**Issue by strohfeuer** [2fast-team/2fast#70]
Add support for Yubikey token to protect access to 2FA tokens.
https://de.wikipedia.org/wiki/YubiKey

**Comment by jp-weber** [comment]
Can you explain in more detail which feature exactly is to be supported? Currently Yubikey is supported for Windows Hello for Business:
https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings?source=recommendations
And for local devices:
https://yubikey.com.ua/en/using-yubikey-with-windows-10
https://www.youtube.com/watch?v=Fp96iTxk0RU
