### ISSUE TITLE
When deleting an entry, you have to wait for the undo timer to expire for the button to re-activate

### ISSUE THREAD

**Issue by Mertsch** [2fast-team/2fast#72]
## Describe the bug

When deleting an entry, you have to wait for the undo timer to expire for the button to re-activate

## Steps to Reproduce
1. Delete a OTP
2. Try to delete a second OTP

## Expected behavior
Delete should always be possible.

## Screenshots
![2023-06-04 15-12-25 ApplicationFrameHost](https://github.com/2fast-team/2fast/assets/9402861/1f39ced1-08f1-4a10-9e5c-e910af84b597)

## Environment

App Version(s): 1.2.6.0

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Insider Build ({build_number})
- [x] This list is outdated 😜 (10 22H2)

**Comment by jp-weber** [comment]
This is a a built-in safety feature to not delete all accounts at a small time frame. In which case should several accounts be deleted at once or one after the other?

**Comment by Mertsch** [comment]
Good point.
I was cleaning up my accounts which I have previously migrated to a different app. If not for that case, you are right about hardly ever deleting multiple accounts.
