### ISSUE TITLE
Accounts are automatically deleted

### ISSUE THREAD

**Issue by NGNler** [2fast-team/2fast#73]
## Describe the bug

After approx. 2 weeks the registered Accounts are automatically deleted and it´s necessary to set up new accounts.

## Steps to Reproduce

1. Given the following environment
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

## Environment

App Version(s):

Windows 10/11 Build Number:
- [x] Windows 10 May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Windows 11 22H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
Can you say more about your settings? is your file on cloud storage? Are multiple devices accessing it? Does the last change to the data file match the use of the application?

The application does not simply delete accounts. Accounts are only deleted through interaction by the user.

**Comment by NGNler** [comment]
My personal file is saved in a network folder. The files from my collegues are saved in the clients „Documents“ Folder.
What do you mean with „Does the last change to the data file match the use of the application?“ ?

Von: Jan Philipp Weber ***@***.***>
Gesendet: Donnerstag, 15. Juni 2023 19:17
An: 2fast-team/2fast ***@***.***>
Cc: Daniel Irrgang ***@***.***>; State change ***@***.***>
Betreff: Re: [2fast-team/2fast] Accounts are automatically deleted (Issue #73)


Can you say more about your settings? is your file on cloud storage? Are multiple devices accessing it? Does the last change to the data file match the use of the application?

The application does not simply delete accounts. Accounts are only deleted through interaction by the user.

**Comment by jp-weber** [comment]
> My personal file is saved in a network folder. The files from my collegues are saved in the clients „Documents“ Folder. What do you mean with „Does the last change to the data file match the use of the application?“ ? 

If the last edit time on the data file correspond with the use of the app. Is the data file from your colleagues also empty?
