### ISSUE TITLE
Choco install 2fast does not install.. just downloads have to install manually.

### ISSUE THREAD

**Issue by pvrwizard** [2fast-team/2fast#81]
## Describe the bug

CHOCO install 2fast does not install the application, it only downloads it. install has to be manually run. 
When trying to script this install for multiple machines it installs under the system account which does not allow the install.

## Steps to Reproduce

Install Chocolatey
command prompt
c:\programdata\chocolatey\bin
PS C:\ProgramData\chocolatey\bin> choco install 2fast -y --force
Chocolatey v2.2.2
Installing the following packages:
2fast
By installing, you accept licenses for the packages.
Progress: Downloading 2fast 1.2.6... 100%

2fast v1.2.6 (forced)
2fast package files install completed. Performing other installation steps.
Downloading 2fast 64 bit
  from 'https://github.com/2fast-team/2fast/releases/download/v1.2.6/Project2FA.UWP_1.2.6.0_Store_Installer.zip'
Progress: 100% - Completed download of C:\Users\preed\AppData\Local\Temp\chocolatey\2fast\1.2.6\Project2FA.UWP_1.2.6.0_Store_Installer.zip (404.17 MB).
Download of Project2FA.UWP_1.2.6.0_Store_Installer.zip (404.17 MB) completed.
Hashes match.
Extracting C:\Users\preed\AppData\Local\Temp\chocolatey\2fast\1.2.6\Project2FA.UWP_1.2.6.0_Store_Installer.zip to C:\ProgramData\chocolatey\lib\2fast\tools...
C:\ProgramData\chocolatey\lib\2fast\tools
 The install of 2fast was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\2fast\tools'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

## Expected behavior

Expected the package to continue with running the install.ps1

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [X] Windows 11 22H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
Is the installation of the application done in user mode on the different computers, or does it happen in system mode? I have not yet tried the installation myself via choco on different computers, only via Intunes and Microsoft Store reference.

@Xav83 
Would you know what that could be?

**Comment by Xav83** [comment]
Hi @jp-weber :slightly_smiling_face: ,

The fact that the package doesn't run the script `install.ps1` is an issue from the Chocolatey package.
If you look at the [chocolateyInstall.ps1 chocolatey script](https://github.com/Xav83/chocolatey-packages/blob/develop/automatic/2fast/tools/chocolateyInstall.ps1#L13), you can see that it only installs the zip, but doesn't attempt to run the script `install.ps1`.
I can try to add a step in order to run this script :slightly_smiling_face: .

**Comment by Xav83** [comment]
Hi @pvrwizard @jp-weber,

I have made an attempt to correct this issue, and the fix I have made is preset in the [new chocolatey package for the version 1.2.7 beta version](https://community.chocolatey.org/packages/2fast/1.2.7-beta). Feel free to try it and to notify me if there is any issue with it (or if everything works correctly :wink:)

**Comment by jp-weber** [comment]
@Xav83 
Thank you! I will test the pre release package 😊

**Comment by jp-weber** [comment]
Works great, thx! ❤

![grafik](https://github.com/2fast-team/2fast/assets/10946850/b5ff1981-8092-4465-a87c-6f0c7cb07672)

**Comment by Xav83** [comment]
![giphy](https://github.com/2fast-team/2fast/assets/6787157/a42bee46-717d-42eb-9651-8f2160d746b9)
