### ISSUE TITLE
Exception from HRESULT: 0x8007000F)

### ISSUE THREAD

**Issue by cdia126** [2fast-team/2fast#82]
## Describe the bug

Unable to get past this error message after entering correct password

I am asked to enter password then once i hit enter this error message pops up

## Steps to Reproduce

1. Given the following environment
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17 at Project2FA.Services.DataService.<CheckLocalDatafile>d__53.MoveNext() + 0x881

## Expected behavior

    i cant screensot this

## Environment

App Version(s):

Windows 10/11 Build Number:
- [ ] Windows 10 May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Windows 11 22H2 Update (22621)
- [ ] Insider Build ({build_number})
Edition	Windows 11 Home
Version	23H2
Installed on	‎12/‎12/‎2022
OS build	22631.2338

**Comment by jp-weber** [comment]
Does the error appear every time after entering the password? Have you reset the application once and did this bring an improvement?

**Comment by jp-weber** [comment]
Can you deinstall and reinstall the app? Can you copy the file to another place? Preferably another partition or usb stick. To me it looks like the app can't access the file and aborts when trying.

**Comment by cdia126** [comment]
So how do I find the files from the app?  I have this app tied to my crypto and now I can not access or trade it nothing
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cdia126** [comment]
You app is an absolute joke and so is yur customer service.  Just say you can fix your product and that I am fucked because I trusted the made up reviews about your product.  Should have known

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Christine ***@***.***>
Sent: Wednesday, September 20, 2023 10:27 PM
To: ***@***.***>
Subject: RE: [2fast-team/2fast] Exception from HRESULT: 0x8007000F) (Issue #82)

So how do I find the files from the app?  I have this app tied to my crypto and now I can not access or trade it nothing
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jp-weber** [comment]
Your tone of voice is completely out of the question. Are you really complaining that you get delayed answers for a free open source project that is only maintained by me?

Regarding your question with the file, here I mean the data file that you defined at the beginning of the setup.
