### ISSUE TITLE
Specified cast is not valid error

### ISSUE THREAD

**Issue by Nancas08** [2fast-team/2fast#87]
## Describe the bug

Specified cast is not valid.

## Steps to Reproduce

1. I enter the app
2. It asked me to turn on the file system and I turned it on
3. Try to log in back but the app was reset
4. I try it to recovered by the local path and click submit
5. See error

Specified cast is not valid.

## Expected behavior

Log in on the app and recover the codes

## Screenshots

![image](https://github.com/2fast-team/2fast/assets/145411252/cba50128-dbfd-4a39-9ab3-9a5737ffaa2c)

## Environment

App Version(s):

Windows 10/11 Build Number:
- [X ] Windows 10 May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Windows 11 22H2 Update (22621)
- [ ] Insider Build ({build_number})

**Comment by jp-weber** [comment]
So you had already set up and used the app before? 

Can you back up the data file you created for the app once?
After the step you can reinstall the app and load the data file. The authorization for the file system is always required for **loading the file**, after the authorization has been set the error should no longer occur.
