### ISSUE TITLE
QR Code scanning broken in Beta/Dev/Canary

### ISSUE THREAD

**Issue by dongle-the-gadget** [2fast-team/2fast#88]
## Describe the bug

Microsoft has recently published a change to screen clipping in the Beta, Dev and Canary builds of Windows. In particular, the Screen Snipping app has been replaced by Snipping Tool, which doesn't support the `edit` action 2fast is using. This causes the Snipping Tool main window to show up instead.

## Steps to Reproduce

1. Install the latest Beta, Dev or Canary build.
2. Update Snipping Tool to version 11.2307.44.0 or higher.
3. Change the `ms-screenclip` handler to "Snipping Tool" in Settings.
4. Open and unlock 2fast, select "Add account" and choose "Scan key - QR Code".
5. Notice that the main Snipping Tool window opens up instead of screen clipping.

**Related code:**
https://github.com/2fast-team/2fast/blob/aa77936944ad75d8c4211ae788929e88cc669e19/Project2FA.Shared/ViewModels/Base/AddAccountViewModelBase.cs#L271

## Expected behavior

Screen snipping launches instead of the main Snipping Tool window.

## Screenshots

N/A since 2fast hides its windows.

## Environment

App Version(s): 1.2.6.0

Windows 10/11 Build Number:
- [ ] Windows 10 May 2020 Update (19041)
- [ ] Windows 11 21H2 Update (22000)
- [ ] Windows 11 22H2 Update (22621)
- [x] Insider Build (23545)

## Additional context

Could be fixed by removing the `edit` verb. Would also work with the legacy Screen Snipping app, from my test on that build.

**Comment by jp-weber** [comment]
I have installed the version 11.2307.48.0 in my Win11 VM and it works as aspected. I think this was a bug in the dev versions. The program call without ```edit``` would not work at least with windows 10.

https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-screen-snipping

**Comment by dongle-the-gadget** [comment]
Are you sure you have set the protocol as mentioned? The bug will not reproduce if you don't do that.

**Comment by jp-weber** [comment]
Ah sorry right, but the change of the handler has to happen manually? What is the intention to change the handler here?
![grafik](https://github.com/2fast-team/2fast/assets/10946850/bb21248d-8df8-4414-861d-f0c22a60ac15)

**Comment by dongle-the-gadget** [comment]
I'd assume that Microsoft would change it to Snipping Tool by default in a future update (after all, they have done this - or attempted to - in Beta builds). This bug only reproduces when Snipping Tool is being used to trigger snipping, and not Screen Snipping.
