### ISSUE TITLE
Microsoft office 365 2fa

### ISSUE THREAD

**Issue by galax20002** [2fast-team/2fast#90]
Hi 

im trying to ad my Office 365 account to this app on windows. but it doesnt work
it etiher says no information is given in the qr code or if i use the number it says the code is in base32 and i cant write 0, 1 and 9 into it. but the code from microsoft has those numbers

**Comment by jp-weber** [comment]
I think this might be the proprietary version from Microsoft. you would have to click the option to get the QR code for the TOTP standard displayed,

![assets_-LSGVtOTYUIkVBoYtFvK_-Ma0d_OHfWHoSpIB9UsH_-Ma0f2nSEgIZhPdmZQef_Screen Shot 2021-05-18 at 3](https://github.com/2fast-team/2fast/assets/10946850/f6f89fae-5c52-4bd4-abe5-08451e5d0f9e)

**Comment by jp-weber** [comment]
With TOTP the base32 standard is used for the secret key. Only A-Z and 2-7 are valid.
https://en.wikipedia.org/wiki/Base32

With my Microsoft account, it works as it should:
![grafik](https://github.com/2fast-team/2fast/assets/10946850/0ef2ef87-f976-438d-a792-e6d361d753a5)
![grafik](https://github.com/2fast-team/2fast/assets/10946850/b73fef0d-0bd6-4833-a040-b461ff0662df)

![grafik](https://github.com/2fast-team/2fast/assets/10946850/a48d20bc-12d8-49a5-86f4-b683fa9405e7)

**Comment by galax20002** [comment]
ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh i think im dumb. just forget it hahaha. i didnt pressed on i want to use a different one. it didnt looked like a link i couldnt click it... ok 
ima close that thanks

**Comment by cgi-member** [comment]
I followed exactly as mentioned
