### ISSUE TITLE
[Feature] Add support to Aegis Exported 2FA Keys via .json, .txt or .html format 

### ISSUE THREAD

**Issue by SUFandom** [2fast-team/2fast#91]
## Describe the problem this feature would solve

The importing limitation should be lessen and just a few click of a mouse to import than manually go to each website and renew OTP for 2Fast and Aegis

This added feature, also should easily port the 2FA accounts from Aegis (A 2FA manager in mobile: https://github.com/beemdevelopment/Aegis since it has an export function. )

## Describe the solution

A seamless cross-compatibility of import and exporting should solve the barrier of trying to do longer manual importing by manually importing credentials or refresh the 2Auth conf in the account settings

## Describe alternatives you've considered

Cant say anything for now

## Additional context & Screenshots

Aegis Export all 2Auth keys > Import to 2Fast > easy import/transfer around lots of 2authed accounts

**Comment by jp-weber** [comment]
duplicate #42
The export of accounts, except for the already existing function of the QR code display, is not planned.
