### ISSUE TITLE
[Question]Where did 2fast go. it is not in Microsoft store anymore. is there anyway to install this without the Microsoft store?

### ISSUE THREAD

**Issue by msav72** [2fast-team/2fast#92]

**Comment by jp-weber** [comment]
Nothing has changed. Which from which country is your request? https://apps.microsoft.com/detail/9P9D81GLH89Q

The app can also installed via the msix installer. 
https://github.com/2fast-team/2fast/releases/tag/v1.2.6

**Comment by msav72** [comment]
It was gone for about an hour. I sent a error report to Microsoft. I
presume it was an issue on their side. I am in the USA.  It is back now
just seemed strange that it disappeared.

**Comment by jp-weber** [comment]
As this was only a temporary problem, I am closing the issue.
